# Generated by Django 4.2.1 on 2023-05-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetions',
            new_name='Quetion',
        ),
    ]
